### ISSUE TITLE
Segregate Past Organisers Section by Year

### ISSUE THREAD

**Issue by meisabhishekpatel** [ContriHUB/ContriHUB-24#165]
It would be helpful to segregate the "Past Organisers" section in such a way that it shows only a list of years initially. When a specific year is clicked, the organisers of that year are displayed, while the organisers from other years remain hidden. However, the organisers of the current year should always remain visible by default.

#### Feature Requirements:

1. **Year List Display:** 
   - Display only the list of years in the "Past Organisers" section initially.
   - Each year should be clickable.

2. **Year-Based Toggle:** 
   - On clicking a particular year, show the organisers of that year.
   - Hide organisers from other years when one year is selected.

3. **Current Year Display:** 
   - The organisers of the current year should always remain visible, irrespective of any toggle action for past years.

#### Benefits:
- This will make the "Past Organisers" section more organised and easier to navigate.
- It reduces the clutter and ensures users can easily access the organisers of specific years without scrolling through large lists.

**Comment by Hersheys-commits** [comment]
hellow **_@meisabhishekpatel_** i want to work on this issue

**Comment by meisabhishekpatel** [comment]
well @Hersheys-commits you did not request it throught the contrihub website to can't assign you

**Comment by PotterHead20** [comment]
@meisabhishekpatel I have requested assignment via Contrihub, please assign this issue to me

**Comment by dhruvordangi** [comment]
Hello everyone I have been assigned this issue. Thank u

**Comment by shikharpandya0487** [comment]
Thanks for assigning the issue . I will start working on it

**Comment by CoderFleet** [comment]
Thanks @meisabhishekpatel for assigning me this issue I will start working on it right away

**Comment by PotterHead20** [comment]
@meisabhishekpatel thanks, i will start working on it

**Comment by meisabhishekpatel** [comment]
by rules only @shikharpandya0487  is assigned this issue.

**Comment by Devu0503** [comment]
can you assign this issue to me

**Comment by meisabhishekpatel** [comment]
@Devu0503 assigned this issue to you now

**Comment by Devu0503** [comment]
@meisabhishekpatel i am unable to run the code in the after cloning it can you guide through the commands to run it

**Comment by meisabhishekpatel** [comment]
@Devu0503 did you refer to this file ?
https://github.com/ContriHUB/ContriHUB-24/blob/main/CONTRIBUTING.md

**Comment by Devu0503** [comment]
no , thanks  now i am able to know how to do

**Comment by Rockyoudead8** [comment]
hey @meisabhishekpatel  can you assign this issue to me i have requested an contrihub and there i got the assignment by you

**Comment by meisabhishekpatel** [comment]
@Rockyoudead8 you can start working on the issue

**Comment by Rockyoudead8** [comment]
Sir I have one request can I submit the project till 6pm , my project is
ready sir but there is a power cut in my area from morning and I can't open
my device for submitting and my time limit is going to over near at 4pm ,
sir will it be okay , I can send you my project sample also if you want sir
plzz help

**Comment by mishra376** [comment]
@meisabhishekpatel please assign me the issue. I have made a assignment request on contrihub.
