### ISSUE TITLE
Different card color based on levels in list View

### ISSUE THREAD

**Issue by meisabhishekpatel** [ContriHUB/ContriHUB-24#166]
Extension of #issue161 of this repo

implement the different color based on difficulty in this list view as well

![image](https://github.com/user-attachments/assets/1b9f4d98-8c5b-464b-8a36-82c0eac04449)

**Comment by harish08102004** [comment]
Hey @meisabhishekpatel I can work in this.

**Comment by UjjwalBaranwal** [comment]
hey @meisabhishekpatel i want to work on this

**Comment by meisabhishekpatel** [comment]
by rules of contriHUB this issue is assigned to @UjjwalBaranwal

**Comment by meisabhishekpatel** [comment]
acctually there not only 3 levels if you see the code carefully there are more level of difficulty also the color should be same as how they are displayed in other view.

**Comment by UjjwalBaranwal** [comment]
thanks for helping me out 
may i take 2 day to understand the codebase and to solve it as i am new to open source and python is not my forte

**Comment by meisabhishekpatel** [comment]
No, you must raise an PR before the time expires otherwise if you raise PR after the time limit your PR will not be reviewed.

**Comment by UjjwalBaranwal** [comment]
hey i am getting error in setting up the project 
as i created my virtual environment and then started to install requiremetn.txt but it started to giving some 
pls help me out 
thank you
![image](https://github.com/user-attachments/assets/d86405f1-be0a-4ed2-859c-c63aa93e0b2c)

**Comment by dhruvordangi** [comment]
I have also been assigned this issue, thank u

**Comment by meisabhishekpatel** [comment]
@UjjwalBaranwal your time expired

**Comment by meisabhishekpatel** [comment]
@dhruvordangi you are assigned the issue now.

**Comment by harish08102004** [comment]
Hey @meisabhishekpatel I asked for this before dhruvordangi.

**Comment by meisabhishekpatel** [comment]
Well @harish08102004 you didn't follow the rules

**Comment by harish08102004** [comment]
What?, which rule are you talking about ?

**Comment by meisabhishekpatel** [comment]
So the issue is now assigned to @ShouryaMishra2006

**Comment by Devu0503** [comment]
can you assign this issue to me

**Comment by meisabhishekpatel** [comment]
issue is solved #174  so closing this issue
