### ISSUE TITLE
Filter Issues by Difficulty Level for Easier Contribution

### ISSUE THREAD

**Issue by meisabhishekpatel** [ContriHUB/ContriHUB-24#167]
### Filter Issues by Difficulty Level for Easier Contribution

It would be very helpful for contributors if they could filter issues based on difficulty level. This would allow contributors to pick tasks that suit their experience level, making the contribution process more streamlined and efficient.

#### Feature Requirements:

1. **Issue Filtering:** 
   - Add a feature to filter the existing issues on the website based on difficulty levels (e.g., "Easy," "Medium," "Hard").
   - The filter should allow users to view only issues of a specific difficulty.

2. **Difficulty Tags:**
   - Each issue should be tagged with a difficulty level (e.g., "Easy," "Medium," "Hard").
   - Tags should be consistently assigned to issues based on their complexity.

#### Benefits:
- This feature will allow contributors to pick issues aligned with their skill level, improving the overall efficiency of contributions.
- It will reduce confusion for new contributors who may find it hard to choose the right issues to work on.

**Comment by DeshDeepakKushwaha** [comment]
can u assign this issue to me

**Comment by nandani-01** [comment]
i want to work on this issue . can u assign this to me

**Comment by meisabhishekpatel** [comment]
@nandani-01 this issue is already assigned see after 2 days if it's still open

**Comment by nandani-01** [comment]
@meisabhishekpatel okey

**Comment by Aryan10** [comment]
Can you assign this to me? Also some clarification, the filter needs to be implemented at the dashboard right?

**Comment by Aryan14021974** [comment]
It is assigned to me

**Comment by Aryan14021974** [comment]
Sir what is the work Flow of the project i didn't get it from the structure

**Comment by Aryan14021974** [comment]
> @Aryan10 yes it needs to be implemented on the dashboard

sir how to run project

**Comment by meisabhishekpatel** [comment]
@Aryan14021974 did you go through the docs it's clearly mentioned here https://github.com/ContriHUB/ContriHUB-24/blob/main/CONTRIBUTING.md

**Comment by Aryan10** [comment]
I have this issue on ContriHUB site but its not assigned here.

**Comment by Aryan14021974** [comment]
> @Aryan14021974 did you go through the docs it's clearly mentioned here https://github.com/ContriHUB/ContriHUB-24/blob/main/CONTRIBUTING.md

sir i have followed all the steps but some issues occured...and my project is not running

**Comment by meisabhishekpatel** [comment]
@Aryan14021974 what's the issue elaborate?

**Comment by Aryan14021974** [comment]
> @Aryan14021974 what's the issue please elaborate?

Sir when i am trying to activate my python environment then is show me 
PS D:\ContriHub> powershell -ExecutionPolicy Bypass -File .\Aryan\Scripts\activate
Processing -File '.\Aryan\Scripts\activate' failed because the file does not have a '.ps1' extension. Specify a valid Windows PowerShell script file name, and then try again.
so I skipped this part and try to run the project but it's not running.

**Comment by Aryan14021974** [comment]
I add homepage and authentication url as
HOMPAGE_URL='http://127.0.0.1:8000/'
AUTHORIZATION_CALLBACK_URL='http://127.0.0.1:8000/'
in .env

**Comment by meisabhishekpatel** [comment]
> > @Aryan14021974 what's the issue please elaborate?
> 
> Sir when i am trying to activate my python environment then is show me PS D:\ContriHub> powershell -ExecutionPolicy Bypass -File .\Aryan\Scripts\activate Processing -File '.\Aryan\Scripts\activate' failed because the file does not have a '.ps1' extension. Specify a valid Windows PowerShell script file name, and then try again. so I skipped this part and try to run the project but it's not running.

well you can definitely skip this part because it is just making virtual env, but it is recommended to create a virtual env for project due to conflicts in version of packages, also to solve that you can try using fullname of file .\Aryan\Scripts\activate.ps1
Also try python3.8 to run the project




> I add homepage and authentication url as HOMPAGE_URL='http://127.0.0.1:8000/' AUTHORIZATION_CALLBACK_URL='http://127.0.0.1:8000/' in .env

are you using this sample_env  well I forgot to add the db changes, we now MySQL instead of sqlite to you need to fill these details to,I have updated the env, also we have a base url now to to you'll need to write HOMPAGE_URL and AUTHORIZATION_CALLBACK_URL according to that
https://github.com/ContriHUB/ContriHUB-24/blob/main/sample_env_file.txt

**Comment by Aryan14021974** [comment]
sir what to fill in which section in DB

**Comment by Aryan10** [comment]
![image](https://github.com/user-attachments/assets/26c342c0-017d-42cf-8655-f47b7b45dcf9)
@meisabhishekpatel Am I supposed to work on this issue, I have it assigned to me on the ContriHUB site but it seems @Aryan14021974 is working on it.

**Comment by meisabhishekpatel** [comment]
> @meisabhishekpatel sir what to fill in which section in DB

it is clearly mentioned in the sample env what you need file for the field.

**Comment by meisabhishekpatel** [comment]
@Aryan10 well you both requested at the same time and So I assigned you both this issue, So you can start too if you want to.

**Comment by Aryan14021974** [comment]
Sir this is my .env file config.
after running python migrate cmd it show error
django.db.utils.OperationalError: (2002, "Can't connect to server on 'localhost' (10061)")
![Screenshot 2024-10-13 121811](https://github.com/user-attachments/assets/cc8aa7d1-e896-44f4-8704-a99e1e524a59)

**Comment by meisabhishekpatel** [comment]
@Aryan14021974 do you have you MySQL server running on your system ?

**Comment by Aryan14021974** [comment]
> @Aryan14021974 do you have you MySQL server running on your system ?

No... I have mongoDb

**Comment by Aryan14021974** [comment]
> @Aryan14021974 do you have you MySQL server running on your system ?
No...I have mongoDB

**Comment by meisabhishekpatel** [comment]
@Aryan14021974 well you need to setup mysql server in your system first and then fille the entries in env

**Comment by Aryan14021974** [comment]
@meisabhishekpatel sir i have modify the code and added the filter by difficulty feature but unable to test it as it need authorization for filteration functionallity and issues must be available to filter.......so can you plz test my code.

**Comment by Aryan14021974** [comment]
> > @meisabhishekpatel sir i have modify the code and added the filter by difficulty feature but unable to test it as it need authorization for filteration functionallity and issues must be available to filter.......so can you plz test my code.
> 
> Firstly test it from your end by populating issues in your own database then I'll check

ok sir i will try

**Comment by Aryan14021974** [comment]
@meisabhishekpatel Sir I have tested it from my side and it's working fine....now what i have to do

**Comment by meisabhishekpatel** [comment]
> @meisabhishekpatel Sir I have tested it from my side and it's working fine....now what i have to do

raise a PR

**Comment by Aryan14021974** [comment]
> > @meisabhishekpatel Sir I have tested it from my side and it's working fine....now what i have to do
> 
> raise a PR

@meisabhishekpatel sir but site is down

**Comment by meisabhishekpatel** [comment]
@Aryan14021974 well I meant on github at that time nvm you already did that

**Comment by Aryan14021974** [comment]
@meisabhishekpatel  Sir plz check my PR request.

**Comment by meisabhishekpatel** [comment]
@Aryan14021974 sorry I forgot I'll check

**Comment by RITIK-CHAUDHRY** [comment]
i have applied through contrihub. may i get this project to work upon @meisabhishekpatel

**Comment by meisabhishekpatel** [comment]
@RITIK-CHAUDHRY it's already solved so no

**Comment by Gprakhar141** [comment]
I have been assigned this issue on contrihub website,should I start working on it???

**Comment by meisabhishekpatel** [comment]
@Gprakhar141 yes

**Comment by Gprakhar141** [comment]
@meisabhishekpatel Sir I have raised a PR for this issue. Please review it.

**Comment by meisabhishekpatel** [comment]
@Gprakhar141 send the PR through contrihub website as well

**Comment by Gprakhar141** [comment]
@meisabhishekpatel Sir please review it else the timer on the website will go out. There are 2 hours remaining.
