### ISSUE TITLE
Display number of Issues solved as well in the Rankings (To solve this first solve solve #169 issue)

### ISSUE THREAD

**Issue by meisabhishekpatel** [ContriHUB/ContriHUB-24#168]
#### Description:
Currently, the ranking page displays the following information:
- Rank
- Username
- Total Points
- Bonus
- Deducted Points

We need to enhance the ranking page by adding a new column that displays the **total number of issues solved by each user**.

#### Acceptance Criteria:
- Add a new column titled "Issues Solved" on the ranking page.
- Display the total number of issues solved by each user in this column.
- Ensure that the column is displayed properly and aligns well with the existing columns (Rank, Username, Total Points, Bonus, Deducted Points).
- The information should be fetched dynamically, ensuring that it reflects the most up-to-date data.

#### Notes:
- Make sure the user interface remains clean and responsive after this change.
- Verify that the sorting functionality (if applicable) works correctly with this new column.

**Comment by DeshDeepakKushwaha** [comment]
can u assign this issue to me

**Comment by meisabhishekpatel** [comment]
@DeshDeepakKushwaha please request throught contrihub website first.

**Comment by meisabhishekpatel** [comment]
also to do this issue you need to complete #169

**Comment by VishalMinj** [comment]
Done 
![image](https://github.com/user-attachments/assets/282f2bf8-43ef-4d3e-836d-b8bdf89ec731)

**Comment by VishalMinj** [comment]
I'm making the pr
