### ISSUE TITLE
Implement feature where User can see how many Issues they have solved Level Wise

### ISSUE THREAD

**Issue by meisabhishekpatel** [ContriHUB/ContriHUB-24#169]
#### Description:
We want to implement a feature where users can view the number of issues they have solved, categorized by difficulty level. This should be similar to how LeetCode displays problems as **Easy**, **Medium**, and **Hard**, with counts for each.

#### Acceptance Criteria:
- Display the number of issues solved by the user, broken down into difficulty levels such as:
  - **Very-Easy** 
  - **Easy**
  - **Medium**
  - **Hard**
- A new section should be added to the user's profile or dashboard page, showing:
  - Total issues solved
  - Issues solved per level (Easy, Medium, Hard)
- Ensure the data is updated dynamically based on the user's activity.

#### UI Requirements:
- The section should be visually clear and easy to read, with level-wise counts displayed in a table or card format.
- Consider using different colors or icons for each difficulty level to make the UI more intuitive (e.g., green for Easy, yellow for Medium, red for Hard).
- Example layout: 
![image](https://github.com/user-attachments/assets/991af729-6c2e-4360-8777-ab7c3a8f26b1)

**Comment by VishalMinj** [comment]
Hello, 
I'd like to study your repo & build a solution around this issue. Can you please suggest which file/directory do I need to go through also how's it tracking the PR's the of the participants?

**Comment by meisabhishekpatel** [comment]
@VishalMinj for working on this issue you need to request through contrihub website

**Comment by wenayy** [comment]
i am not able to understand properly the code base like could you please help how should i do it it's a lot of .py file i am not able to comprehend i got that frontend thing but the functionality is all verbose to me

**Comment by meisabhishekpatel** [comment]
@wenayy if you didn't knew anything about the tech stack why did you straight away jumped into solving the issue

**Comment by meisabhishekpatel** [comment]
I explain you some part of codebase which you are having any doubt but if you don't know a stack then how can I explain you the whole tech stack

**Comment by wenayy** [comment]
the issue was simple but a lot of .py file overwhelmed me

**Comment by wenayy** [comment]
but in open source you need not know the stack fully you learn eventually by learnnign and open source is all about helping too for enriching the community and what is the tech stack can you tell of this codebase

**Comment by wenayy** [comment]
a lot of .py files it was very new to me so initally i got stuck

**Comment by meisabhishekpatel** [comment]
@wenayy  i know that, but you should atleast know in what you are getting your hands into,
Btw its Django with MySQL as database

**Comment by VishalMinj** [comment]
Please assign me this issue @meisabhishekpatel

**Comment by meisabhishekpatel** [comment]
@VishalMinj did you request through contrihub website ?

**Comment by VishalMinj** [comment]
Yes!

**Comment by VishalMinj** [comment]
Hey @meisabhishekpatel 
where will I get these?
![image](https://github.com/user-attachments/assets/49c26916-35f4-4e2a-960a-5e970fcc5d6d)

also, is backports.zoneinfo important for local setup?

**Comment by VishalMinj** [comment]
hey @meisabhishekpatel  what CSS lib. have you used in here?

**Comment by meisabhishekpatel** [comment]
@VishalMinj well it's mostly bootstrap only you see all the cdn link here 
https://github.com/ContriHUB/ContriHUB-24/blob/main/home/templates/base.html

**Comment by VishalMinj** [comment]
ok, I have one more doubt? are the tag info stored some where in the db or we need to get it through github?

**Comment by VishalMinj** [comment]
hey @meisabhishekpatel  
I've kinda came up with a solution, please clear up my query so I can test out.
I've created a new table to hold all the level info and setup a one to one relation with the user.
I need to know if there is a html doc for the project author to accept or reject the pr or is it all through email?

**Comment by VishalMinj** [comment]
Thanks for response @meisabhishekpatel 
![image](https://github.com/user-attachments/assets/7f938437-f567-44db-bb3d-b84f14ea4998)
This is the model I have added. I too thought of redundancy but it doesn't look like you're saving this info any where, please correct me if I'm wrong.
Also this is the card layout I've added
![image](https://github.com/user-attachments/assets/c6a36bc1-547d-4847-9730-3531f3bcc58c)
 and finally one issue I'm facing rn is to test my implementation.
![image](https://github.com/user-attachments/assets/760fd3a1-5ebb-41f0-a2d3-3d5f3aa21217)
 I've added this line in judge_pr where my solution is to send the code of level and based on the code level increment the particular level count. But since the pr are accepted via email, I'm unable to pinpoint the config. for that

**Comment by VishalMinj** [comment]
Thanks for responding @meisabhishekpatel ,
I Just noticed that once the pr is accepted and verified the contributor can check it from the pr's submit section.
Just tell me this what kind of linkage is established between the accepted pr and the contributer?

I can use that info, iterate over it and populate the card on the profile.
Btw here's the design I came up with
![image](https://github.com/user-attachments/assets/908d4d4b-e6ea-41f6-b59d-4b56e9eccabe)

**Comment by VishalMinj** [comment]
I think I'm done now! My solution to filter issue form Pullrequest is working, for the most part. The email service was not working so I did manual transection and pr acceptance from admin. And it worked as soon as i accepted the pr status.

![image](https://github.com/user-attachments/assets/1822215c-ff11-4c83-a490-1f49ca31dc69)

If you will allow then i'd like to make pr. The only problem is, that i'm not assigned from contrihub website so how will i make the pr request over there?

**Comment by meisabhishekpatel** [comment]
> , for the most part.

what do you mean by this.

> The email service was not working so I did manual transection

why ??

**Comment by VishalMinj** [comment]
> > what do you mean by this.
> What i mean is i haven't tried it via email acceptance. That's how it works right? By sending email to the auther and then he accepts or reviews.
> > why ??
> Well i tried my best to set up the email config. But it was throwing some error regarding thread. So I did the issue assignment and Pr acceptance from.the admin panel

**Comment by meisabhishekpatel** [comment]
@VishalMinj what's the error exactly this might break things so you need to test that and them make PR

**Comment by VishalMinj** [comment]
Well, Here's the error. Occurs when I try to access any of mail functionality from helper.py

![image](https://github.com/user-attachments/assets/cbb352c3-5ca6-4937-be50-16334ff3576e)

Probably coming from somewhere around here

![image](https://github.com/user-attachments/assets/3a7a75f8-c041-4315-9f28-145c15b6f61e)

As far as thing go on breaking I haven't touched much only added an objects query in the profile view and the card component.
Not a bother for me to test out data flow with email but idk how to config the email set up properly. I've done what was mentioned in the README like adding host user and password. I don't know what to do beyond that

**Comment by meisabhishekpatel** [comment]
@VishalMinj did you properly setup the env ?

**Comment by meisabhishekpatel** [comment]
Also show me complete error, also what are you filling in env to setup email service

**Comment by VishalMinj** [comment]
this is the full error

![image](https://github.com/user-attachments/assets/5f306ef0-ae17-45f7-8d2e-30bdb37bd62a)

this is what I set up in env

![image](https://github.com/user-attachments/assets/806c6047-79b4-4262-87a2-dde9d7d6f8be)

this was the response on frontend

![image](https://github.com/user-attachments/assets/c479fba8-5bd4-4b9f-9d02-38c7e160a95d)

**Comment by VishalMinj** [comment]
Was there a need to give an email id while creating a super user?

**Comment by meisabhishekpatel** [comment]
no, you can use any temp mail for creating a super user

**Comment by meisabhishekpatel** [comment]
@VishalMinj are you using this on college proxy or not ?

**Comment by VishalMinj** [comment]
No, i shifted to cellular while testing

**Comment by VishalMinj** [comment]
hey, I manage to receive the email

![image](https://github.com/user-attachments/assets/8e7fdc1a-d16d-4edd-9c24-ad101c139064)

Apparently this exception disappeared after I upgraded my django version. Now, how to accept the assignment request ?

**Comment by meisabhishekpatel** [comment]
You have to go to maintainers userprofile to accept

**Comment by VishalMinj** [comment]
how to create that account?

**Comment by VishalMinj** [comment]
I GLAD TO SHARE IT'S WORKING 😭
![image](https://github.com/user-attachments/assets/2e0ad121-7f2d-49ca-80f3-b218b217f3e1)

**Comment by meisabhishekpatel** [comment]
Ok I'll review it can you send PR through contriHUB website

**Comment by VishalMinj** [comment]
Done

**Comment by meisabhishekpatel** [comment]
this issue is closed now

**Comment by meisabhishekpatel** [comment]
@VishalMinj solve for very-easy tag as well

**Comment by VishalMinj** [comment]
hey I've added the very-easy issue list. Couldn't do much with ui, using external styling library is my weakness. Here's the preview, I'm making the pr
![image](https://github.com/user-attachments/assets/2328bc1a-50f6-4ee7-8ab6-8cc0dde9fe94)

**Comment by meisabhishekpatel** [comment]
@VishalMinj maintain consistency (very-easy Prob -> very-easy issue)

**Comment by meisabhishekpatel** [comment]
@VishalMinj also create a PR request
