### ISSUE TITLE
Submitting the PR link  issue

### ISSUE THREAD

**Issue by haseeb-555** [ContriHUB/ContriHUB-24#172]
![Screenshot 2024-10-10 035701](https://github.com/user-attachments/assets/6d6aa132-7bc0-416b-b480-52ffa5b15643)

after clicking it redirects to some other page

![Screenshot 2024-10-10 040159](https://github.com/user-attachments/assets/ba2924c5-3ddc-4255-a9af-9122528a1ea5)

**Comment by meisabhishekpatel** [comment]
Thats not an issue I'll update the link soon, for requesting PR you have to to profile section
I am closing this issue.
