### ISSUE TITLE
Filter Issues by Status for Easier Contribution

### ISSUE THREAD

**Issue by meisabhishekpatel** [ContriHUB/ContriHUB-24#188]
### **Filter Issues by Status for Easier Contribution**

To make the contribution process more efficient, it would be helpful if contributors could filter issues based on their current status (open or closed). This would allow contributors to focus on tasks that are still available and easily reference completed issues.

#### **Issue Filtering:**
- Add a feature to filter the existing issues on the website based on their status (e.g., "Open" or "Closed").
- The filter should allow users to view only issues of a specific status.
- Users should be able to toggle between open and closed issues for a better overview of available and completed tasks.

### **Benefits:**
- This feature will allow contributors to focus on open issues that they can work on, improving the overall efficiency of contributions.
- Viewing closed issues can help contributors understand how similar problems were solved in the past.
- It will reduce confusion for contributors by clearly distinguishing available tasks from completed ones.

**Comment by hexwhiz** [comment]
@meisabhishekpatel done adding the filter. PR opened.
