### ISSUE TITLE
redirection issue in like and dislike

### ISSUE THREAD

**Issue by meisabhishekpatel** [ContriHUB/ContriHUB-24#190]
Clicking the like or dislike button on an issue card currently redirects to an incorrect route. Please update the route to redirect to the dashboard where all issues are listed.

**Comment by VishalMinj** [comment]
Is this assigned to someone?

**Comment by meisabhishekpatel** [comment]
@VishalMinj yes it is assigned

**Comment by meisabhishekpatel** [comment]
Closed
